Add integration spec and fix n+1 problems
abiola-arobieke/blog-app pull request #8
Opened 2023-08-09 10:34 UTC by abiola-arobieke

In this milestone:

2023-08-09 13:28 UTC, julie-ify reviewed
Hi @abiola-arobieke,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly collaborate with your coding partner(s).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-10 10:24 UTC, DammyShittu requested changes
Hi @abiola-arobieke and @sameedmohsin28,

## Highlights
✔️ Passing tests

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 10:24 UTC, DammyShittu commented on spec/views/users/show.html.erb_spec.rb
> +end
- [ ] The test for checking the number of posts a user has is missing. Kindly add it.

2023-08-10 10:24 UTC, DammyShittu commented on spec/views/posts/index.html.erb_spec.rb
> +  end
- [ ] Out of your 27 test cases, this test failed. Kindly fix it.

  ![image](https://github.com/abiola-arobieke/blog-app/assets/54848363/fb20a4b1-6202-4d9d-8707-2554aac1e0dd)

2023-08-10 11:20 UTC, DammyShittu requested changes
Hi @abiola-arobieke and @sameedmohsin28,

## Highlights
✔️ Passing tests

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 11:20 UTC, DammyShittu commented on spec/views/users/show.html.erb_spec.rb
> +end
- [ ] You marked [this request](https://github.com/abiola-arobieke/blog-app/pull/8#discussion_r1289884136) as resolved but you have not fixed it.

  Kindly add the test for checking the number of posts a user has written in the user show page.

2023-08-10 11:37 UTC, ShadyShawkat approved these changes
## Hi @abiola-arobieke, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 21:37 UTC, merged